export const colorOptions = [
  { name: 'Barn Red', color: '#9E280E', imposingImagePath: 'barn-red' },
  { name: 'Black', color: '#000000', imposingImagePath: 'black' },
  { name: 'White', color: '#E5E5E7', imposingImagePath: 'white' },
  { name: 'Quaker Gray', color: '#54575A', imposingImagePath: 'quaker-gray' },
  { name: 'King Blue', color: '#3787c5', imposingImagePath: 'king-blue' },
  { name: 'Clay', color: '#9E958C', imposingImagePath: 'clay' },
  { name: 'Cardinal Red', color: '#9E032A', imposingImagePath: 'cardinal-red' },
  { name: 'Earth Brown', color: '#5E3D32', imposingImagePath: 'earth-brown' },
  { name: 'Evergreen', color: '#375543', imposingImagePath: 'ever-green' },
  { name: 'Slate Blue', color: '#3E718A', imposingImagePath: 'slate-blue' },
  { name: 'Beige', color: '#E4DEC5', imposingImagePath: 'beige' },
  { name: 'Pewter Gray', color: '#898C8D', imposingImagePath: 'pewter-gray' },
  { name: 'Sandstone', color: '#CECAAB', imposingImagePath: 'sandstone' },
  { name: 'Tan', color: '#BC9F82', imposingImagePath: 'tan' },
  { name: 'True Burgundy', color: '#79242F', imposingImagePath: 'true-burgundy' },
  { name: 'Vintage Burgundy', color: '#522B39', imposingImagePath: 'vintage-burgundy' },
  {
    name: 'Stone Wall',
    color: '#A9A9A9',
    imgUrl: '/images/stone-wall.png',
    imposingImagePath: 'rock-1',
  },
  {
    name: 'Rich Oak Wood',
    color: '#8B5A2B',
    imgUrl: '/images/rich-oak-wood.png',
    imposingImagePath: 'wood-3',
  },
  {
    name: 'Rustic Brick',
    color: '#8B3A3A',
    imgUrl: '/images/rustic-brick.png',
    imposingImagePath: 'rock-3',
  },
  {
    name: 'Black Wood',
    color: '#2B2B2B',
    imgUrl: '/images/blackwood.png',
    imposingImagePath: 'wood-4',
  },
];
